In [2]:
#base (Python 3.11.5)
# import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import csv

In [24]:
sm = pd.read_csv("C:/Users/solis/Desktop/Research/CC/SM/GS-series-matrix.csv")
sm1 = sm # making a copy to use later

In [25]:
probe_id = sm['ID_REF']
probe_id = probe_id[:-1]
probe_id # probe ids from the original series-matrix
spID = sm1.iloc[:, 0]
spID

0                       1007_s_at
1                         1053_at
2                          117_at
3                          121_at
4                       1255_g_at
                   ...
54671              AFFX-ThrX-M_at
54672             AFFX-TrpnX-3_at
54673             AFFX-TrpnX-5_at
54674             AFFX-TrpnX-M_at
54675    !series_matrix_table_end
Name: ID_REF, Length: 54676, dtype: object

In [26]:
gene = pd.read_csv('gene-conversion.csv')
pID = gene.iloc[:, 0]
colTo=gene.iloc[:, 1]
colGene = gene.iloc[:, 3]
toList = colTo.unique()
geneList = colGene.unique()

In [27]:

homoID = []
for p in pID:
    for idx, s in enumerate(spID):  # Track index properly
        if p == s:
            homoID.append(idx)  # Store the correct index
            break  # Stop once we find the first match

In [28]:
h2 = homoID.copy()
h2.sort()
reducedSM2 = sm.loc[h2]

In [7]:
homoID

[25524,
 29400,
 28411,
 35061,
 3936,
 30725,
 40510,
 37340,
 27084,
 34062,
 40157,
 41354,
 32899,
 29882,
 11826,
 52488,
 37328,
 51645,
 31667,
 27989,
 363,
 27569,
 19203,
 52468,
 2477,
 15734,
 10442,
 53815,
 18727,
 7490,
 12384,
 22280,
 532,
 44867,
 9459,
 53803,
 29258,
 11297,
 19725,
 38732,
 41366,
 1947,
 17430,
 53839,
 32539,
 34231,
 1522,
 21504,
 31589,
 16602,
 28920,
 11528,
 1053,
 3928,
 31588,
 40522,
 23299,
 17390,
 3079,
 47061,
 1012,
 44036,
 22268,
 16565,
 50283,
 44855,
 44189,
 18616,
 42688,
 34206,
 43145,
 29388,
 46169,
 31262,
 14558,
 21812,
 30737,
 2411,
 38653,
 19191,
 27557,
 30370,
 23694,
 16102,
 29425,
 53369,
 10525,
 39630,
 28436,
 18673,
 43133,
 5746,
 30761,
 32935,
 38641,
 41811,
 15710,
 13069,
 33465,
 21873,
 53370,
 19756,
 35085,
 50344,
 548,
 1435,
 7120,
 11298,
 12153,
 27749,
 46217,
 27062,
 40486,
 29810,
 53357,
 30749,
 47073,
 44048,
 1832,
 46168,
 17720,
 17030,
 16566,
 37304,
 15722,
 17875,
 630,
 54346,
 17751,
 29834,
 18715,
 23108,
 20037,
 27935,
 20153,
 46230,
 31613,
 20835,
 3962,
 35073,
 6568,
 17901,
 54169,
 38629,
 38152,
 4056,
 34219,
 40498,
 29833,
 29236,
 20590,
 2226,
 21261,
 42737,
 9467,
 37316,
 10173,
 885,
 32170,
 539,
 23170,
 29437,
 16971,
 10280,
 53827,
 26196,
 53394,
 50729,
 24021,
 12013,
 28435,
 1045,
 23112,
 23485,
 17477,
 14831,
 44916,
 29821,
 41775,
 3972,
 13505,
 32037,
 31739,
 23182,
 853,
 36437,
 41787,
 9204,
 567,
 1809,
 11334,
 11898,
 27977,
 13493,
 32948,
 18375,
 32354,
 24480,
 12514,
 19773,
 4049,
 48708,
 51572,
 50258,
 14843,
 17829,
 42725,
 48426,
 24468,
 8251,
 11322,
 41402,
 11082,
 35976,
 32972,
 14382,
 24009,
 18775,
 20270,
 23193,
 31240,
 31131,
 36449,
 17481,
 19377,
 14486,
 32095,
 45620,
 2629,
 16231,
 17465,
 14819,
 54241,
 45567,
 32010,
 31625,
 25652,
 30496,
 36412,
 41762,
 30314,
 13871,
 5477,
 41799,
 842,
 32936,
 25358,
 11697,
 17459,
 33045,
 47977,
 10841,
 25282,
 40474,
 19499,
 24898,
 11024,
 21375,
 27562,
 24456,
 44434,
 18762,
 54434,
 9448,
 42713,
 34664,
 12753,
 27379,
 4375,
 24732,
 13813,
 30557,
 18744,
 4899,
 34243,
 38710,
 28796,
 40473,
 31118,
 1509,
 30340,
 8696,
 8659,
 25021,
 20282,
 28387,
 25363,
 47965,
 33844,
 42840,
 48439,
 41378,
 22293,
 16553,
 12571,
 52873,
 29785,
 22872,
 5213,
 42072,
 6320,
 6049,
 44024,
 22292,
 19557,
 49440,
 48093,
 23543,
 54377,
 33517,
 26230,
 10417,
 864,
 37749,
 31106,
 36424,
 557,
 24910,
 20637,
 5022,
 11791,
 20128,
 24444,
 18750,
 10033,
 1803,
 52861,
 1668,
 38893,
 25892,
 13630,
 19142,
 28784,
 48438,
 44941,
 29797,
 36425,
 43096,
 30740,
 46652,
 5468,
 34191,
 14370,
 33338,
 15274,
 29254,
 16946,
 13926,
 14058,
 48857,
 6842,
 18188,
 25953,
 1158,
 52849,
 5191,
 33380,
 970,
 17535,
 36024,
 36025,
 33370,
 39038,
 36376,
 23504,
 13093,
 53443,
 17520,
 1150,
 2813,
 20987,
 16107,
 36845,
 29103,
 46664,
 27807,
 54291,
 33392,
 11269,
 9972,
 12325,
 2714,
 31725,
 26257,
 40027,
 16967,
 50667,
 4914,
 40031,
 2964,
 16957,
 20515,
 39050,
 5182,
 36012,
 46642,
 178,
 49858,
 38192,
 13105,
 14183,
 16094,
 45809,
 47522,
 5673,
 22737,
 42783,
 8027,
 32552,
 15355,
 34561,
 9858,
 35556,
 25742,
 26245,
 21212,
 37038,
 48811,
 6828,
 30242,
 524,
 11394,
 22762,
 21051,
 20375,
 6851,
 10045,
 13469,
 4940,
 26287,
 7329,
 29229,
 5479,
 30279,
 19118,
 47534,
 16131,
 2832,
 20169,
 41333,
 787,
 30868,
 32597,
 33642,
 825,
 35147,
 13252,
 4767,
 4613,
 18361,
 46630,
 22725,
 19863,
 1167,
 37255,
 29278,
 39085,
 22774,
 8743,
 20093,
 29311,
 45845,
 6868,
 9064,
 48799,
 36400,
 35988,
 586,
 27864,
 3311,
 39014,
 17237,
 49859,
 26269,
 40039,
 23640,
 834,
 2372,
 13939,
 36388,
 3557,
 36916,
 2841,
 23066,
 16119,
 39097,
 29217,
 43256,
 3394,
 46617,
 46688,
 642,
 5231,
 27931,
 10455,
 50655,
 31143,
 43059,
 5485,
 19785,
 8019,
 36000,
 5697,
 25082,
 22713,
 21861,
 39026,
 35146,
 11582,
 23568,
 4931,
 42281,
 15262,
 49800,
 23579,
 7603,
 13942,
 13481,
 45833,
 40098,
 39966,
 17516,
 36928,
 21465,
 21849,
 4400,
 5897,
 51584,
 17539,
 13022,
 5486,
 16178,
 33439,
 30982,
 38977,
 40931,
 35953,
 20023,
 42749,
 10480,
 23664,
 29449,
 31980,
 5812,
 42269,
 28460,
 32457,
 45772,
 19739,
 48786,
 35941,
 35460,
 52537,
 498,
 34158,
 37291,
 18799,
 28733,
 8723,
 22690,
 1184,
 10504,
 16058,
 5169,
 16165,
 13034,
 34170,
 46713,
 17018,
 22691,
 3345,
 37267,
 45784,
 30925,
 7334,
 5492,
 38156,
 10651,
 22666,
 19226,
 35134,
 14744,
 10395,
 20088,
 18811,
 3375,
 51112,
 40943,
 3319,
 16166,
 33696,
 544,
 6777,
 5224,
 44892,
 27304,
 27001,
 10468,
 40086,
 1178,
 49602,
 48774,
 36940,
 22443,
 3951,
 52525,
 40907,
 12828,
 40073,
 19236,
 30112,
 50704,
 23688,
 13184,
 21824,
 1530,
 15167,
 36049,
 21629,
 7320,
 32433,
 13118,
 34182,
 4404,
 38279,
 18490,
 11028,
 51609,
 31179,
 5767,
 38965,
 3425,
 39990,
 40074,
 34194,
 19351,
 15732,
 11211,
 45808,
 40061,
 35098,
 39072,
 29241,
 17912,
 16070,
 33405,
 30310,
 2146,
 1471,
 44880,
 1392,
 10766,
 50763,
 1188,
 17900,
 29871,
 21572,
 36037,
 27545,
 12943,
 9985,
 48762,
 41848,
 40919,
 33763,
 24746,
 1570,
 41797,
 15154,
 18548,
 16994,
 6833,
 22245,
 36363,
 12202,
 1243,
 29253,
 35925,
 39060,
 35110,
 16082,
 26760,
 30300,
 18303,
 30992,
 30255,
 3405,
 10337,
 40002,
 50692,
 25693,
 5177,
 27544,
 43998,
 33417,
 54362,
 25025,
 18558,
 16418,
 27095,
 9948,
 46304,
 50196,
 13559,
 20385,
 9029,
 31226,
 13140,
 2130,
 52981,
 34329,
 5260,
 35892,
 49474,
 19223,
 41002,
 24563,
 33551,
 40599,
 47026,
 7350,
 12961,
 15442,
 31566,
 4511,
 37362,
 52993,
 18705,
 38676,
 34569,
 19235,
 35904,
 29905,
 10276,
 7840,
 24551,
 4344,
 24564,
 19613,
 16227,
 5397,
 17032,
 288,
 1048,
 41858,
 12721,
 34341,
 23810,
 41015,
 35880,
 35905,
 50677,
 41870,
 20487,
 3626,
 11143,
 12315,
 764,
 28048,
 9961,
 61,
 17820,
 20560,
 24576,
 16239,
 46568,
 19971,
 17053,
 39116,
 14034,
 11649,
 15475,
 9168,
 33451,
 34557,
 31554,
 7160,
 39146,
 32840,
 15781,
 1224,
 20475,
 23845,
 53648,
 44058,
 35917,
 38097,
 19248,
 12697,
 48454,
 41771,
 12698,
 29354,
 13897,
 10212,
 26586,
 307,
 9010,
 20838,
 23507,
 40557,
 231,
 20102,
 29476,
 32864,
 5412,
 11840,
 35868,
 14277,
 31202,
 5470,
 23183,
 9424,
 34605,
 2553,
 37375,
 34353,
 18178,
 26711,
 4233,
 47605,
 16544,
 44059,
 41039,
 17041,
 38109,
 32384,
 47002,
 29366,
 8853,
 31542,
 4129,
 25510,
 14010,
 5278,
 39855,
 12949,
 13932,
 24286,
 1438,
 40833,
 46556,
 2248,
 23762,
 7808,
 52430,
 38700,
 18687,
 14629,
 15191,
 52968,
 28036,
 22729,
 2074,
 25670,
 41027,
 27,
 20740,
 23424,
 11150,
 47014,
 15793,
 28795,
 16720,
 489,
 43521,
 32852,
 10615,
 35856,
 35929,
 1931,
 25057,
 27066,
 20893,
 25011,
 1209,
 30486,
 9390,
 21717,
 30193,
 22199,
 14481,
 367,
 35189,
 5237,
 11830,
 37411,
 26334,
 47581,
 29329,
 22,
 35604,
 38133,
 27076,
 52560,
 39109,
 53042,
 2064,
 20321,
 15805,
 1210,
 54430,
 13010,
 21385,
 25520,
 44095,
 18734,
 2415,
 49895,
 44544,
 13382,
 47569,
 38749,
 20848,
 15818,
 21478,
 51233,
 23520,
 20557,
 46593,
 28618,
 7854,
 41262,
 30194,
 18656,
 820,
 26715,
 16299,
 480,
 47568,
 14493,
 43928,
 39121,
 35449,
 41051,
 23054,
 9407,
 276,
 1201,
 15485,
 23544,
 21705,
 43014,
 5428,
 38146,
 10348,
 32397,
 44185,
 16534,
 12264,
 19052,
 13394,
 1309,
 31436,
 30691,
 38121,
 35592,
 242,
 36904,
 51956,
 29353,
 51208,
 18668,
 25115,
 4310,
 13745,
 16202,
 23948,
 43929,
 11685,
 15812,
 30068,
 44532,
 479,
 2534,
 28302,
 37436,
 34593,
 18365,
 46990,
 13358,
 39134,
 24527,
 35568,
 27330,
 15842,
 4322,
 35853,
 1453,
 18834,
 6119,
 46569,
 17449,
 43545,
 51741,
 31190,
 28247,
 15228,
 18232,
 21527,
 ...]

In [29]:
indexSix = pd.read_csv("indexPos.csv")
indexSix.iloc[:, 0]
row_list = indexSix.iloc[:,0].values.flatten().tolist()
# row_list = row_list[1:]
row_list.append(0)
row_list.sort()

In [ ]:
sb_1 = pd.read_csv("subgroups/cancerOrder-S1.csv").loc[:,'pid'].to_list()
sb_2 = pd.read_csv("subgroups/cancerOrder-S2.csv").loc[:,'pid'].to_list()
sb_3 = pd.read_csv("subgroups/cancerOrder-S3.csv").loc[:,'pid'].to_list()
sb_4 = pd.read_csv("subgroups/cancerOrder-S4.csv").loc[:,'pid'].to_list()
sb_breast = pd.read_csv("subgroups/cancerOrder-Breast.csv").loc[:,'pid'].to_list()
sb_lung = pd.read_csv("subgroups/cancerOrder-Lung.csv").loc[:,'pid'].to_list()
sb_colon = pd.read_csv("subgroups/cancerOrder-Colon.csv").loc[:,'pid'].to_list()
sb_kidney = pd.read_csv("subgroups/cancerOrder-Kidney.csv").loc[:,'pid'].to_list()
sb_uterus = pd.read_csv("subgroups/cancerOrder-Uterus.csv").loc[:,'pid'].to_list()
sb_ovary = pd.read_csv("subgroups/cancerOrder-Ovary.csv").loc[:,'pid'].to_list()

In [30]:
reducedSM = sm.loc[homoID]
# reducedSM2 = reducedSM2.copy
reducedSM = reducedSM.iloc[:, row_list]
reducedSM

,ID_REF,GSM38051,GSM38054,GSM38055,GSM38057,GSM38058,GSM38059,GSM38060,GSM38061,GSM38062,...,GSM353928,GSM353929,GSM353930,GSM353931,GSM353933,GSM353935,GSM353937,GSM353939,GSM353941,GSM353943
25524,216232_s_at,1088.1,935.9,1216.0,1348.9,1034.4,705.9,643.7,866.2,990.7,...,670.2,660.9,626.9,653.8,1041.8,1018.1,994.4,1092.0,1608.4,1318.9
29400,220116_at,40.0,62.4,81.9,86.8,761.5,49.0,82.9,61.8,175.3,...,86.9,133.2,61.1,248.9,84.5,134.4,243.4,56.4,230.3,109.1
28411,219127_at,1379.9,1037.5,1660.2,1114.9,777.6,1122.2,940.3,1042.1,1171.0,...,113.0,700.3,2132.9,267.2,325.0,217.6,478.7,3015.0,1266.3,85.6
35061,225804_at,587.5,542.5,417.6,706.6,378.6,419.7,462.6,580.1,896.3,...,863.1,706.9,1172.3,807.8,767.3,54.3,673.4,678.0,767.4,366.0
3936,1557848_at,9.8,16.1,20.8,21.8,14.9,41.2,84.3,87.4,7.5,...,171.7,306.8,120.8,119.2,18.2,16.1,72.9,15.6,25.1,23.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24199,214904_at,125.9,95.2,72.0,11.9,75.5,92.6,115.9,59.0,120.7,...,127.9,102.4,40.0,68.6,10.7,14.8,67.0,70.2,8.0,100.8
33791,224530_s_at,8.6,6.8,6.1,6.9,6.6,5.0,20.6,9.9,5.3,...,104.4,267.1,199.7,83.3,18.4,9.9,9.9,20.3,5.7,10.5
28168,218884_s_at,327.1,323.0,391.6,430.4,458.6,301.7,311.4,262.0,537.5,...,241.9,411.5,243.2,322.2,312.8,248.8,154.8,230.4,355.1,632.4
33312,224038_at,17.4,16.8,9.4,26.4,12.4,74.0,5.3,7.0,39.5,...,138.4,139.6,58.3,78.3,140.9,23.9,127.8,11.2,16.0,62.1
35954,226699_at,34.5,25.0,92.3,7.2,106.7,25.5,27.3,112.1,29.7,...,38.9,12.7,22.8,31.9,11.5,48.3,22.3,24.7,36.6,34.8

In [31]:
reducedSM_s1 = reducedSM.loc[:, ['ID_REF'] + sb_1]
reducedSM_s2 = reducedSM.loc[:, ['ID_REF'] + sb_2]
reducedSM_s3 = reducedSM.loc[:, ['ID_REF'] + sb_3]
reducedSM_s4 = reducedSM.loc[:, ['ID_REF'] + sb_4]
reducedSM_breast = reducedSM.loc[:, ['ID_REF'] + sb_breast]
reducedSM_lung = reducedSM.loc[:, ['ID_REF'] + sb_lung]
reducedSM_colon = reducedSM.loc[:, ['ID_REF'] + sb_colon]
reducedSM_kidney = reducedSM.loc[:, ['ID_REF'] + sb_kidney]
reducedSM_uterus = reducedSM.loc[:, ['ID_REF'] + sb_uterus]
reducedSM_ovary = reducedSM.loc[:, ['ID_REF'] + sb_ovary]

check if there were any nan values in reducedSM (which is used to calculate the median for value for all genes)

In [32]:
gene = pd.read_csv('gene-conversion.csv')
gene2 = gene.copy

gene2 = gene.assign(Index=homoID)
gene2

,From,To,Species,Gene Name,Index
0,216232_s_at,10985,Homo sapiens,GCN1 activator of EIF2AK4(GCN1),25524
1,220116_at,3781,Homo sapiens,potassium calcium-activated channel subfamily ...,29400
2,219127_at,79170,Homo sapiens,proline rich 15 like(PRR15L),28411
3,225804_at,124936,Homo sapiens,cytochrome b5 domain containing 2(CYB5D2),35061
4,1557848_at,101929084,Homo sapiens,long intergenic non-protein coding RNA 2401(LI...,3936
...,...,...,...,...,...
44499,214904_at,7592,Homo sapiens,zinc finger protein 41(ZNF41),24199
44500,224530_s_at,80333,Homo sapiens,potassium voltage-gated channel interacting pr...,33791
44501,218884_s_at,60558,Homo sapiens,GTP binding elongation factor GUF1(GUF1),28168
44502,224038_at,100287932,Homo sapiens,translocase of inner mitochondrial membrane 23...,33312
44503,226699_at,89848,Homo sapiens,FCH and double SH3 domains 1(FCHSD1),35954

In [ ]:
# for the entire 6 cancers and also for the subgroups
import pandas as pd

# Step 1: Reshape `gene2` into long format for faster lookup
gene_long = gene2.melt(id_vars=gene2.columns[0], var_name="col", value_name="Gene")
gene_long = gene_long.drop(columns=["col"]).dropna()  # Drop unnecessary column
gene_long = gene_long.rename(columns={gene_long.columns[0]: "ID_REF"})  # Ensure first column is 'PI'

# Step 2: Filter only the relevant PIs for the given genes
gene_filtered = gene_long[gene_long["Gene"].isin(geneList)]

# Step 3: Merge once instead of filtering repeatedly
merged_df = gene_filtered.merge(reducedSM, on='ID_REF', how="left")
# Step 4: Compute mean efficiently using groupby()
final_geneAvg = merged_df.drop(columns=["ID_REF"]).groupby("Gene").mean()
# Display the final DataFrame
# final_geneAvg.iloc[:, row_list]
final_geneAvg
final_geneAvg.to_csv('Gene-Average.csv')

In [38]:
import pandas as pd

# Step 1: Reshape `gene2` into long format for faster lookup
gene_long = gene2.melt(id_vars=gene2.columns[0], var_name="col", value_name="Gene")
gene_long = gene_long.drop(columns=["col"]).dropna()  # Drop unnecessary column
gene_long = gene_long.rename(columns={gene_long.columns[0]: "ID_REF"})  # Ensure first column is 'PI'

# Step 2: Filter only the relevant PIs for the given genes
gene_filtered = gene_long[gene_long["Gene"].isin(geneList)]

# Step 3: Merge once instead of filtering repeatedly
merged_df = gene_filtered.merge(reducedSM_ovary, on='ID_REF', how="left")
# Step 4: Compute mean efficiently using groupby()
final_geneAvg = merged_df.drop(columns=["ID_REF"]).groupby("Gene").mean()
# Display the final DataFrame
# final_geneAvg.iloc[:, row_list]
final_geneAvg
final_geneAvg = final_geneAvg.round(2)
final_geneAvg.to_csv('Gene-Average_Ovary.csv')

In [ ]:
# #sanitary check - want to use og and use on 10 instances 
# geneAvg_list2 = []  # Store mean expression DataFrames for each gene

# for gene in geneList:
#     # **Step 1: Filter gene2 for matching genes efficiently**
#     val = gene2[gene2.iloc[:, 1:].apply(lambda row: gene in row.values, axis=1)]  # Assuming gene is in any column (excluding the first column)

#     # **Step 2: Extract relevant column values**
#     samePI = val.iloc[:, 0].tolist()  # Assuming the first column contains PI
    
#     # **Step 3: Use `.isin()` instead of looping**
#     temp_df = reducedSM[reducedSM.iloc[:, 0].isin(samePI)]  # Assuming first column in reducedSM contains PI values
    
#     if not temp_df.empty:
#         # **Step 4: Drop metadata column & compute mean**
#         temp1 = temp_df.iloc[:, 1:]  # Drop the first column (PI)
#         geneAvg = temp1.mean(axis=0).to_frame().T  # Compute mean and transpose
#         geneAvg.index = [gene]  # Set the gene name as the index

#         geneAvg_list2.append(geneAvg)

# # **Step 5: Concatenate all computed means**
# if geneAvg_list2:
#     final_geneAvg = pd.concat(geneAvg_list2)
# else:
#     final_geneAvg = pd.DataFrame()  # Return empty DataFrame if nothing found

# # Display the final DataFrame
# print(final_geneAvg)

In [ ]:
# final_geneAvg.to_csv('Gene-Average.csv')

In [39]:
final_geneAvg = pd.read_csv('Gene-Average.csv')
final_geneAvg1 = pd.read_csv('Gene-Average_s1.csv')
final_geneAvg2 = pd.read_csv('Gene-Average_s2.csv')
final_geneAvg3 = pd.read_csv('Gene-Average_s3.csv')
final_geneAvg4 = pd.read_csv('Gene-Average_s4.csv')
final_geneAvgB = pd.read_csv('Gene-Average_Breast.csv')
final_geneAvgL = pd.read_csv('Gene-Average_Lung.csv')
final_geneAvgC = pd.read_csv('Gene-Average_Colon.csv')
final_geneAvgK = pd.read_csv('Gene-Average_Kidney.csv')
final_geneAvgO = pd.read_csv('Gene-Average_Ovary.csv')
final_geneAvgU = pd.read_csv('Gene-Average_Uterus.csv')
# final_geneAvg = final_geneAvg.round(2) # for top 6
final_geneAvg1.loc[:, 'Gene']

0                1,4-alpha-glucan branching enzyme 1(GBE1)
1        1-acylglycerol-3-phosphate O-acyltransferase 1...
2        1-acylglycerol-3-phosphate O-acyltransferase 2...
3        1-acylglycerol-3-phosphate O-acyltransferase 3...
4        1-acylglycerol-3-phosphate O-acyltransferase 4...
                               ...
21404            zyg-11 related cell cycle regulator(ZER1)
21405                                zygote arrest 1(ZAR1)
21406                     zymogen granule protein 16(ZG16)
21407                   zymogen granule protein 16B(ZG16B)
21408                                           zyxin(ZYX)
Name: Gene, Length: 21409, dtype: object

In [45]:
shortGene = []
longGene = final_geneAvgC.iloc[:, 0] # list of the entire gene name
for i in longGene:
    lg = i.split(' ')
    last_element = lg[len(lg) - 1]  
    x = last_element.find("(")
    shortGene.append(last_element[x:(len(last_element))])

sG = pd.DataFrame(shortGene, columns=["Gene Name"])
sG

      Gene Name
0        (GBE1)
1      (AGPAT1)
2      (AGPAT2)
3      (AGPAT3)
4      (AGPAT4)
...         ...
21404    (ZER1)
21405    (ZAR1)
21406    (ZG16)
21407   (ZG16B)
21408     (ZYX)

[21409 rows x 1 columns]

In [49]:
copyFGA = final_geneAvgO.copy()
copyFGA
copyFGA.iloc[:,0] = sG
copyFGA.rename(columns={"Unnamed: 0": "Gene Name"}, inplace=True)
# for i in copyFGA:
#     print(i)

copyFGA.to_csv("subgroups/GM-SM-Ovary.csv")

right now everything below is being used

In [49]:
file = open('probe_id.txt','w')
for probe in probe_id:
	file.write(probe+"\n")
file.close()

created the subgroups for deeper dimensionality reduction

In [ ]:
co = pd.read_csv("CO2.csv")

# Initialize subgroup lists
sb_one = []
sb_two = []
sb_three = []
sb_four = []
# sb_breast = [] # not to sure i think this section is unnecessary
# sb_lung = []
# sb_colon = []
# sb_kidney = []
# sb_uterus = []
# sb_ovary = []

# Iterate over rows
for index, row in co.iterrows():
    cancer_type = row['0']
    pid = row['Unnamed: 0']  # Assuming 'Unnamed: 0' is the patient/sample ID
    value = row[1]           # Assuming the second column has relevant values

    if cancer_type == 'Breast':
        sb_one.append([pid, value])
        sb_two.append([pid, value])
        sb_three.append([pid, value])
        sb_breast.append([pid, value])

    if cancer_type == 'Lung':
        sb_one.append([pid, value])
        sb_three.append([pid, value])
        sb_lung.append([pid,value])

    if cancer_type == 'Kidney':
        sb_two.append([pid, value])
        sb_kidney.append([pid,value])

    if cancer_type == 'Colon':
        sb_three.append([pid, value])
        sb_four.append([pid, value])
        sb_colon.append([pid, value])

    if cancer_type == 'Uterus':
        sb_two.append([pid, value])
        sb_four.append([pid, value])  
        sb_uterus.append([pid, value])

    if cancer_type == 'Ovary':
        sb_two.append([pid, value])
        sb_four.append([pid, value])
        sb_ovary.append([pid, value])


# Convert lists to DataFrames
subgroup1 = pd.DataFrame(sb_one, columns=['pid', 'Cancer'])
subgroup2 = pd.DataFrame(sb_two, columns=['pid', 'Cancer'])
subgroup3 = pd.DataFrame(sb_three, columns=['pid', 'Cancer'])
subgroup4 = pd.DataFrame(sb_four, columns=['pid', 'Cancer'])
subgroupB = pd.DataFrame(sb_breast, columns=['pid','Cancer'])
subgroupL = pd.DataFrame(sb_lung, columns=['pid', 'Cancer'])
subgroupC = pd.DataFrame(sb_colon, columns=['pid','Cancer'])
subgroupK = pd.DataFrame(sb_kidney, columns=['pid','Cancer'])
subgroupU = pd.DataFrame(sb_uterus, columns=['pid','Cancer'])
subgroupO = pd.DataFrame(sb_ovary, columns=['pid','Cancer'])

# Save to CSV
# subgroup1.to_csv('cancerOrder-S1.csv', index=False)
# subgroup2.to_csv('cancerOrder-S2.csv', index=False)
# subgroup3.to_csv('cancerOrder-S3.csv', index=False)
# subgroup4.to_csv('cancerOrder-S4.csv', index=False)

subgroupB.to_csv('subgroups/cancerOrder-Breast.csv', index=False)
subgroupL.to_csv('subgroups/cancerOrder-Lung.csv', index=False)
subgroupC.to_csv('subgroups/cancerOrder-Colon.csv', index=False)
subgroupK.to_csv('subgroups/cancerOrder-Kidney.csv', index=False)
subgroupU.to_csv('subgroups/cancerOrder-Uterus.csv', index=False)
subgroupO.to_csv('subgroups/cancerOrder-Ovary.csv', index=False)

In [ ]:
sm_sg1 = subgroup1.iloc[:, 0].astype(str)
sm_sg2 = subgroup2.iloc[:, 0].astype(str)
sm_sg3 = subgroup3.iloc[:, 0].astype(str)
sm_sg4 = subgroup4.iloc[:, 0].astype(str)
sm_breast = subgroupB.iloc[:, 0].astype(str)
sm_lung = subgroupL.iloc[:, 0].astype(str)
sm_colon = subgroupC.iloc[:, 0].astype(str)
sm_kidney = subgroupK.iloc[:, 0].astype(str)
sm_uterus = subgroupU.iloc[:, 0].astype(str)
sm_ovary = subgroupO.iloc[:, 0].astype(str)
geneMap = pd.read_csv("GM-SM.csv")

geneMap_S1 = geneMap.loc[:, geneMap.columns.isin(sm_sg1)]
geneMap_S2 = geneMap.loc[:, geneMap.columns.isin(sm_sg2)]
geneMap_S3 = geneMap.loc[:, geneMap.columns.isin(sm_sg3)]
geneMap_S4 = geneMap.loc[:, geneMap.columns.isin(sm_sg4)]
geneMap_B = geneMap.loc[:, geneMap.columns.isin(sm_breast)]
geneMap_L = geneMap.loc[:, geneMap.columns.isin(sm_lung)]
geneMap_C = geneMap.loc[:, geneMap.columns.isin(sm_colon)]
geneMap_K = geneMap.loc[:, geneMap.columns.isin(sm_kidney)]
geneMap_O = geneMap.loc[:, geneMap.columns.isin(sm_ovary)]
geneMap_U = geneMap.loc[:, geneMap.columns.isin(sm_uterus)]



# geneMap_S1.to_csv("subgroups/GM-SM-1.csv")
# geneMap_S2.to_csv("subgroups/GM-SM-2.csv")
# geneMap_S3.to_csv("subgroups/GM-SM-3.csv")
# geneMap_S4.to_csv("subgroups/GM-SM-4.csv")
geneMap_B.to_csv("subgroups/GM-SM-Breast.csv")
geneMap_L.to_csv("subgroups/GM-SM-Lung.csv")
geneMap_C.to_csv("subgroups/GS-SM-Colon.csv")
geneMap_K.to_csv("subgroups/GS-SM-Kidney.csv")
geneMap_O.to_csv("subgroups/GS-SM-Ovary.csv")
geneMap_U.to_csv("subgroups/GS-SM-Uterus.csv")

In [ ]:


description = pd.read_csv("C:/Users/solis/Desktop/Research/CC/SM/GS-SM-06.csv")
# description = description.iloc[1: ]
# breast_data = pd.read_csv('GS-SM-BREAST.csv')
# colon_data = pd.read_csv('GS-SM-COLON.csv')
# kidney_data = pd.read_csv('GS-SM-KIDNEY.csv')
# ovary_data = pd.read_csv('GS-SM-OVARY.csv')
# uterus_data = pd.read_csv('GS-SM-UTERUS.csv')
# lung_data = pd.read_csv('GS-SM-LUNG.csv')

desc = pd.DataFrame(description.iloc[:, 1:])

In [ ]:
desc1 = description.dropna()
desc1.transpose()
desc1.iloc[1:, 1:]
# desc1.to_csv("SMF-06.csv")
# desc1

In [ ]:

non_numeric_columns = desc1.select_dtypes(exclude=['number']).columns

col = ['ID_REF', 'ID_REF.1', 'ID_REF.2', 'ID_REF.3', 'ID_REF.4']
flipped = desc1.drop(columns=col)
flipped = flipped.iloc[:, 1:]
xa = flipped.columns
xar = pd.DataFrame(xa)

In [ ]:
flipped2 = flipped.transpose()
# flipped2.dtypes
xar.to_csv("fixCanCount.csv")
co = pd.read_csv("CO2.csv")
co